---
title: 'Cal State Northridge | KIN 610 - Quantitative Analysis of Research in Kinesiology'
author: "Ovande Furtado Jr., Ph.D."
date: "Spring 2021"
output:
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    latex_engine: pdflatex
    template: ../../svm-latex-syllabus.tex
  html_document:
    df_print: paged
geometry: margin=1in
subtitle:
email: ovande.furtado@csun.edu
web: drfurtado.us
officehours: By appt. only - http://calendly.com/drfurtado
office: 289 Redwood Hal
classroom: '*online*'
classhours: Fully Online Asynchronous
fontfamily: mathpazo
fontsize: 11pt
header-includes: \linespread{1.05}
---

[^1]: The lowest score will be dropped at the end of the semester.
[^2]: Learning Management System used by [CSUN](https://www.csun.edu/it/canvas)
[^3]: In addition to the download link, you will find the GPower Manual and two publications to help you getting
started.
[^4]: Except for Homeworks. your hand-in assignments must represent your own thoughts (refer to [Academic Dishonesty Policy](#dishonesty) for more information); especially, the information about PLAGIARISM. 

# Course Description & Format

This class focuses on the introductory statistical techniques used in social science research.  Students will be introduced to concepts such as reliability, validity, measures of central tendency, variability, probability, and statistical techniques including: t tests (independent & dependent samples), Analysis of Variance (ANOVA), Chi-square, correlation, and regression.  Students are expected to take the material/concepts presented in class and apply them through a series of homework assignments and quizzes.  The overall goal of the course is not only to help students understand the mathematical/statistical concepts presented but also to assist in the application of these procedures.

This is a Fully Online class (FOI) in which all class sessions and exams are presented in an online environment. FOI courses have no on campus meetings. Online meetings may be a mix of scheduled and/or intermittent meeting times, and anytime access.

---

# Expectations and Goals

Upon completion of this course, you will be able to adequately:

1. Introduce statistical concepts utilized in research within the social sciences
2. Apply the mathematical/statistical techniques presented for social science research
3. Demonstrate an ability to analyze and interpret data within the social sciences
4. Provide practical examples as to when statistical techniques presented are appropriate methods for analysis.

---
 
# Required & Suggested Material

## Textbook {#textbook}

Joseph P. Weir and William J. Vincent. 2021. Statistics in Kinesiology, 5th ed. Champaign, IL: Human Kinetics.

## Other readings:

- Choosing the Correct Statistical Test in SPSS. (n.d.). Retrieved May 5, 2013, from https://goo.gl/3Xg8DF 
- Universität Düsseldorf: Gpower[^3]. (n.d.). Retrieved January 15, 2021, from https://www.psychologie.hhu.de/en/research-teams/cognitive-and-industrial-psychology/gpower.html

## Supplies: {#supplies}

- A calculator (phone is ok)
- JASP Statistical Software (Free) - https://jasp-stats.org/ 
- OSF Account (Free) - https://bit.ly/3ii2Q0Z
- GPower (Free) - https://bit.ly/2LS1VbI

---

# Course Structure and Requirements

You are responsible for the material covered in the textbook prior to attending each class. Please note that the week’s readings are specified in the class schedule (available in Canvas). 

In addition to these readings, the instructor may assign supplemental readings throughout the semester. These supplemental readings do not appear on the schedule as these readings will be assigned at the instructor’s discretion.

The assignments used to enhance your learning experience in this course include:

## Class preparedness

You will be evaluated on your preparedness by submitting an assignment before each class (Major Takeaways). Further details about this assignment will be provided in Canvas.

## Participation & Attendance 

Class presence and participation points are given to encourage your active class participation and discussion.  You will be rewarded with a perfect score **as long as you frequently come to class and actively contribute to the class discussion during lectures**.

Although it is not required, most students send their professor a brief e-mail to explain their absence in advance. Students who repeatedly join the Zoom session late will have their Class Participation grade lowered.

## Quizzes

Following each class, you will complete a multiple-choice quiz on the topic covered in class. You will be given three (3) attempts for each quiz. The final grade for each quiz will be the **average** of the three attempts. Quizzes are due every Sunday at 11:59 p.m.

## Homeworks {#homeworks}

Students will complete three (3) homework assignments in the course of the semester. The purpose of each assignment is to assist students in applying their understanding of the statistical procedures discussed in class as well as to provide an opportunity for students to respond to the readings. 

>>NOTE: You are allowed to discuss homework with other students (and with the instructor), **but you must write final answers yourself**, in your own words. **Solutions prepared “in committee” or by copying or paraphrasing someone else’s work are not acceptable**; your hand-in assignments must represent your own thoughts (refer to [Academic Dishonesty Policy](#dishonesty) for more information); especially, the information about PLAGIARISM.  

## Final Project

You will be required to complete and submit a final project at the end of the semester. In short, you will be given a research question and a data set. Then, you will be asked to run the proper statistical analysis in [JASP](#supplies) and turn in a written report. **In addition, you will be required to present the results of your project to your classmates**. Further information about this assignment will be provided in Canvas.

---

# Course Policy

I will detail the policy for this course below. Basically, don't cheat and try to learn stuff.

## Grading Policy

-   **15%**: Class preparedness[^1]

-   **5%**: Participation & Attendance 

-   **20%**: Weekly Quizzes

-   **20%**: Homeworks

-   **30%**: Final Project (Written report)

-   **10%**: Final Project (Presentation)

## Grading Scale

A 93.00-100.00 | A- 90.00-92.99 
B+ 87.00-89.99 | B 83.00-86.99 | B- 80.00-82.99 
C+ 77.00-79.99 | C 73.00-76.99 | C- 70.00-72.99 
D+ 67.00-69.99 | D 63.00-66.99 | D- 60.00-62.99 
F <59.99 

> _Note 1_: In recognition of the fact that grading, however carefully done, will always be imperfect, this class will utilize a “round up” rule for assigning final grades. I will round up from .5% and above, but anything below this will round down. In other words, 79.5 will round up to 80, while 79.4 will round down to 79 even.

> _Note 2_: Requests for an Incomplete (I) must conform to [university policies](https://bit.ly/3bDxwZi). Among other requirements, “I” is possible only for instances in which you are demonstrating passing work in the class.

## Attendance Policy

> *Showing up is 80 percent of life* -- Woody Allen, [via Marshall Brickman](http://quoteinvestigator.com/2013/06/10/showing-up/#note-6553-1)

Attendance will be taken at the beginning of every class; please, plan accordingly.

## E-mail Policy

I am usually quick to respond to student e-mails. Below, I outline why I will not respond to certain e-mails students send. Multiple rationales follow.

1.  The student could answer his/her own inquiry by reading the syllabus.
2.  The student is protesting a grade without reference to specific points of objection. These e-mails tend to be expressive utility on the part of the student and do not require a response from me. Students interested in improving their knowledge of material should see me during office hours.
3.  The student is requesting an extension on an assignment for which the syllabus already established the deadline. The answer is always "no"; unless you have a reason that can be documented and you contacted me before the deadline.
4.  The student is asking for an extra credit opportunity, a request that amounts to more grading for the professor. The answer is "no".

More e-mail stuff...

- If you have questions concerning assignments, deadlines, etc., please first submit a post to our **Q&A Forum in Canvas**. If a response is not posted within 24 hours (by me or a classmate), you can send me an e-mail **via _inbox_ in Canvas[^2]**. I will typically respond within 24 hours (Monday-Friday).

- If you need to schedule an online meeting via Zoom (https://csun.zoom.us/), you can do so by visiting this link: http://calendly.com/drfurtado. The details will be provided when the meeting is scheduled via Calendly, including the option to cancel/reschedule a meeting, if needed.

## Make-Up Exam Policy

There is no make-up for assignments. Therefore, unless you have discussed your situation with me before the assignment’s due date and we have made other arrangements, a missed assignment results in a grade of zero (see late assignment below). **Note that making “arrangements” will only be possible given the student provides a valid and written excuse from a reputable source**.

## Late Assignments

Unless you have made previous arrangements, a late assignments will be docked 10% per day (first 4 days) it is late. After the fourth day, it will result in a grade of zero. 

## Extra Credit

There is no individual extra credit granted. Therefore, do not plan to make-up poor grades at the end of the semester by asking to do extra credit work. I might provide extra credit opportunities, but these will be offered to the entire class, not to individuals.

## Disabilities Policy

Federal law mandates the provision of services at the university-level to qualified students with disabilities.

This instructor, in conjunction with California State University Northridge, is committed to upholding and maintaining all aspects of the federal Americans with Disabilities Act of 1990 (ADA) and Section 504 of the Rehabilitation Act of 1973. 

If you are a student with a disability and wish to request accommodations, please contact the office of Students with Disabilities Resources located in 110 Student Services Building, or call (818) 677-2684 for an appointment. Any information regarding your disability will remain confidential. Because many accommodations require early planning, requests for accommodations should be made as early as possible. Any requests for accommodations will be reviewed in a timely manner to determine their appropriateness to this setting. 

## Academic Dishonesty Policy {#dishonesty}

_Please, **stop** and read the information below; this is important!_

Each student is expected to be familiar with, and abide by, the conditions of student conduct, as presented in the CSUN Catalog, with emphasis on sections entitled, Student Conduct Code, Academic Dishonesty, Faculty Policy on Academic Dishonesty, and Penalties. Any student engaging in academic dishonesty (e.g., cheating, fabrication, facilitating academic dishonesty, plagiarism) is subject to discipline, which may include a failing grade in the course, and may also be subject to more severe discipline by the University. Students are encouraged to visit the link below and become familiar with the Standards for Student Conduct. 

http://www.csun.edu/a&r/soc/studentconduct.html  

### About Plagiarism

Plagiarism means using words, ideas, or arguments from another person or source without citation[^4]. Cite all sources consulted to any extent (including material from the internet), whether or not assigned and whether or not quoted directly. For quotations, four or more words used in sequence must be set off in quotation marks, with the source identified.  

Plagiarism is a serious violation of the CSUN Student Conduct Code. Please read my comment about plagiarism under [Homeworks](#homeworks). Any form of cheating will immediately earn you a failing grade for the entire course. **By remaining enrolled, you consent to this policy**. 

> Turnitin (see below) will detect such misconducts as it checks every submission against a database of papers, as well as against the Internet. 

What is Turnitin? 

[Turnitin](https://www.turnitin.com/) is an automated system that instructors can use to quickly and easily compare each student's assignment with billions of websites, as well as an enormous database of student papers that grows with each submission. Accordingly, you will be expected to submit assignments through the Canvas Assignment Tool in electronic format. After the assignment is processed, as an instructor, I receive a report from _Turnitin_ that states if and how another author’s work was used in the assignment. 

---

# Final (yet important) Notes

## How to Access our Course and Get Started

- Log into Canvas: https://canvas.csun.edu
- Under “My Courses,” locate our course and click on it.
- This will take you to the course home page. 

## Technology Requirements and Support:

- A computer and access to the internet (reliable connection)
- Google Chrome (web browser)

## What I Expect of You:

1. Plan your schedule to ensure you several hours per week to spend on this class and take time to identify where and when you’ll do your learning.
2. Review the due dates for the assignments (refer to our Course Schedule in Canvas) to orient yourself to the flow of the learning. 
3. This course requires regular engagement and practice using [JASP](#supplies) (Statistical Package).

---

# Class Schedule

Not included here. Please, refer to our Canvas page.