---
title: 'Cal State Northridge | KIN 610 - Quantitative Analysis of Research in Kinesiology'
author: "Ovande Furtado Jr., Ph.D."
date: "Spring 2022"
output:
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    latex_engine: pdflatex
    template: ../../svm-latex-syllabus.tex
  html_document:
    df_print: paged
geometry: margin=1in
subtitle:
email: ovande.furtado@csun.edu
web: drfurtado.us
officehours: By appt. Only (https://calendly.com/drfurtado)
office: 289 Redwood Hal
classroom: 'RE 276'
classhours: Tu 7:00-9:45 pm
fontfamily: mathpazo
fontsize: 11pt
header-includes: \linespread{1.05}
---

> COVID-19 - Please Read!!!

> CSUN is following guidelines from the California Department of Public Health and Los Angeles County Department of Public Health to promote safety during the COVID-19 pandemic for all students, employees, and visitors. [The California State University requires all students and employees to be fully vaccinated against COVID-19 before coming to campus](http://www.csun.edu/ua/email/NCpages/0813_student_vaccination.html), and no later than September 30, 2021, unless an approved exemption has been requested and regular testing is underway. In order to protect against the spread of COVID, all students, employees, and visitors to campus are required to adhere to all health and safety requirements outlined on the [University's website regarding COVID-19](https://www.csun.edu/matadors-forward/health-and-safety).

------------------------------------------------------------------------

# Course Description

This class focuses on the introductory statistical techniques used in social science research. Students will be introduced to concepts such as reliability, validity, measures of central tendency, variability, probability, and statistical techniques including: t tests (independent & dependent samples), Analysis of Variance (ANOVA), Chi-square, correlation, and regression. Students are expected to take the material/concepts presented in class and apply them through a series of homework assignments and quizzes. The overall goal of the course is not only to help students understand the mathematical/statistical concepts presented but also to assist in the application of these procedures.

# Course Format

The format of this course is Traditional face-to-face. However, note that:

> Per CSUN's announcement on January 7, CSUN will begin the spring semester with temporary primarily remote instruction for the first three weeks of the semester, Monday, January 24 through Friday, February 11. We will resume in-person instruction on Monday, February 14. 

## Virtual Classroom Guidelines: 

- Please make sure that the name displayed in Zoom is your real name (first and last);
- I appreciate if you keep your camera on throughout the session, though this is not a requirement; 
- As a courtesy, please try to join the session prior to the start time and participate in the entire session; 
- Respectful behavior and professional courtesy is a requirement at all times; 
- Review any readings, and assignments for the week prior to participating in the weekly session and come prepared with any questions; 
- Keep your microphone on mute if you are not actively speaking in order to reduce background noise; 
- These sessions will **not be recorded** as they are designed for primarily discussion and question and answer sessions; - Please contact a classmate if you miss a session to catch up on any additional information you may have missed. 
- If you plan to keep the video turned on during our Zoom meetings, I will kindly ask you to download and use one of the CSUN backgrounds, instead of using your own or use no background.
  - Examples: https://bit.ly/3pbJb5H (Links to an external site.) 
  - How to install and use: https://bit.ly/3hDl3ow

----

# Expectations and Goals

Upon completion of this course, you will be able to adequately:

1.  Introduce statistical concepts utilized in research within the social sciences
2.  Apply the mathematical/statistical techniques presented for social science research
3.  Demonstrate an ability to analyze and interpret data within the social sciences
4.  Provide practical examples as to when statistical techniques presented are appropriate methods for analysis.

------------------------------------------------------------------------

# Required & Suggested Material

## Textbooks {#textbook}

Danielle Navarro & David Foxcroft. (2019). Learning statistics with jamovi: A tutorial for psychology students and other beginners. <http://learnstatswithjamovi.com/>

## Other readings:

-   Choosing the Correct Statistical Test in SPSS. (n.d.). Retrieved May 5, 2013, from <https://goo.gl/3Xg8DF>
-   Universität Düsseldorf: Gpower[^1]. (n.d.). Retrieved January 15, 2021, from <https://www.psychologie.hhu.de/en/research-teams/cognitive-and-industrial-psychology/gpower.html>

[^1]: In addition to the download link, you will find the GPower Manual and two publications to help you getting started.

## Supplies: {#supplies}

-   A calculator (phone is ok)
-   Jamovi Statistical Software (Free) - <https://www.jamovi.org/>
-   Jamovi Video Tutorials (Free) - <https://bit.ly/2VHvd1w>
-   OSF Account (Free) - <https://bit.ly/3ii2Q0Z>
-   GPower (Free) - <https://bit.ly/2LS1VbI>

------------------------------------------------------------------------

# Course Structure and Requirements

You are responsible for the material covered in the textbook prior to attending each class. Please note that the week's readings are specified in the class schedule (available in Canvas).

In addition to these readings, the instructor may assign supplemental readings throughout the semester. These supplemental readings do not appear on the schedule as these readings will be assigned at the instructor's discretion.

The assignments used to enhance your learning experience in this course include:

## Class preparedness

You will be evaluated on your preparedness by submitting an assignment before each class (Major Takeaways). Further details about this assignment will be provided in Canvas.

## Participation & Attendance

Class presence and participation points are given to encourage your active class participation and discussion. You will be rewarded with a perfect score **as long as you frequently come to class and actively contribute to the class discussion during lectures**.

Although it is not required, most students send their professor a brief e-mail to explain their absence in advance. Students who repeatedly join the Zoom session late will have their Class Participation grade lowered.

## Quizzes

Following each class, you will complete a multiple-choice quiz on the topic covered in class. You will be given three (3) attempts for each quiz. The final grade for each quiz will be the **average** of the three attempts. Quizzes are due every Sunday at 11:59 p.m.

## Homeworks {#homeworks}

Students will complete three (3) homework assignments in the course of the semester. The purpose of each assignment is to assist students in applying their understanding of the statistical procedures discussed in class as well as to provide an opportunity for students to respond to the readings.

> > NOTE: You are allowed to discuss homework with other students (and with the instructor), **but you must write final answers yourself**, in your own words. **Solutions prepared "in committee" or by copying or paraphrasing someone else's work are not acceptable**; your hand-in assignments must represent your own thoughts (refer to [Academic Dishonesty Policy](#dishonesty) for more information); especially, the information about PLAGIARISM.

## Final Project

You will be required to complete and submit a final project at the end of the semester. In short, you will be given a research question and a data set. Then, you will be asked to run the proper statistical analysis in [Jamovi](#supplies) and turn in a written report. **In addition, you will be required to present the results of your project to your classmates**. Further information about this assignment will be provided in Canvas.

------------------------------------------------------------------------

# Course Policy

I will detail the policy for this course below. Basically, don't cheat and try to learn stuff.

## Grading Policy

-   **10%**: Class preparedness[^2]

-   **5%**: Participation & Attendance

-   **20%**: Weekly Quizzes

-   **20%**: Homeworks

-   **30%**: Final Project (Written report)

-   **15%**: Final Project (Presentation)

[^2]: The lowest score will be dropped at the end of the semester.

## Grading Scale

A 93.00-100.00 \| A- 90.00-92.99 B+ 87.00-89.99 \| B 83.00-86.99 \| B- 80.00-82.99 C+ 77.00-79.99 \| C 73.00-76.99 \| C- 70.00-72.99 D+ 67.00-69.99 \| D 63.00-66.99 \| D- 60.00-62.99 F \<59.99

> *Note 1*: In recognition of the fact that grading, however carefully done, will always be imperfect, this class will utilize a "round up" rule for assigning final grades. I will round up from .5% and above, but anything below this will round down. In other words, 79.5 will round up to 80, while 79.4 will round down to 79 even.

> *Note 2*: Requests for an Incomplete (I) must conform to [university policies](https://bit.ly/3bDxwZi). Among other requirements, "I" is possible only for instances in which you are demonstrating passing work in the class.

## Attendance Policy

> *Showing up is 80 percent of life* -- Woody Allen, [via Marshall Brickman](http://quoteinvestigator.com/2013/06/10/showing-up/#note-6553-1)

Attendance will be taken at the beginning of every class; please, plan accordingly.

## E-mail Policy

If you have a question concerning this course (i.e., assignments, content, deadlines, etc.), send a message^[When referring to an assignment, open it online, copy its URL address, and include it as part of your question. Students may also answer questions that are sent to our mailing list.] to our mailing list (provide under Canvas>Home). For any other matters, send me a message at my CSUN email.

Keep it in mind:

1. All students enrolled in my courses are added to the mailing lists automatically. If you are not receiving emails from the mailing address, then contact CSUN Help Desk to get it fixed.
2. Only send messages to the mailing list address when the content is pertinent to ALL students. For private matters, email me directly.
3. ONLY send message to the mailing list address from your CSUN email address; otherwise, your message will not be delivered. 

I am usually quick to respond to student e-mails. Below, I outline why I will not respond to certain e-mails students send. Multiple rationales follow.

1.  The student could answer his/her own inquiry by reading the syllabus.
2.  The student is protesting a grade without reference to specific points of objection. These e-mails tend to be expressive utility on the part of the student and do not require a response from me. Students interested in improving their knowledge of material should see me during office hours.
3.  The student is requesting an extension on an assignment for which the syllabus already established the deadline. The answer is always "no"; unless you have a reason that can be documented and you contacted me before the deadline.
4.  The student is asking for an extra credit opportunity, a request that amounts to more grading for the professor. The answer is "no".

**More e-mail stuff...**

-   If you need to schedule an online meeting via Zoom (<https://csun.zoom.us/>), you can do so by visiting this link: <http://calendly.com/drfurtado>. The details will be provided when the meeting is scheduled via Calendly, including the option to cancel/reschedule a meeting, if needed.

[^3]: **Learning Management System used by [CSUN](https://www.csun.edu/it/canvas)**

## Make-Up Exam Policy

There is no make-up for assignments. Therefore, unless you have discussed your situation with me before the assignment's due date and we have made other arrangements, a missed assignment results in a grade of zero (see late assignment below). **Note that making "arrangements" will only be possible given the student provides a valid and written excuse from a reputable source**.

## Late Assignments

Unless you have made previous arrangements, a late assignments will be docked 10% per day (first 4 days) it is late. After the fourth day, it will result in a grade of zero.

## Extra Credit

There is no individual extra credit granted. Therefore, do not plan to make-up poor grades at the end of the semester by asking to do extra credit work. I might provide extra credit opportunities, but these will be offered to the entire class, not to individuals.

## Disabilities Policy

Federal law mandates the provision of services at the university-level to qualified students with disabilities.

This instructor, in conjunction with California State University Northridge, is committed to upholding and maintaining all aspects of the federal Americans with Disabilities Act of 1990 (ADA) and Section 504 of the Rehabilitation Act of 1973.

If you are a student with a disability and wish to request accommodations, please contact the office of Students with Disabilities Resources located in 110 Student Services Building, or call (818) 677-2684 for an appointment. Any information regarding your disability will remain confidential. Because many accommodations require early planning, requests for accommodations should be made as early as possible. Any requests for accommodations will be reviewed in a timely manner to determine their appropriateness to this setting.

## Academic Dishonesty Policy {#dishonesty}

*Please, **stop** and read the information below; this is important!*

Each student is expected to be familiar with, and abide by, the conditions of student conduct, as presented in the CSUN Catalog, with emphasis on sections entitled, Student Conduct Code, Academic Dishonesty, Faculty Policy on Academic Dishonesty, and Penalties. Any student engaging in academic dishonesty (e.g., cheating, fabrication, facilitating academic dishonesty, plagiarism) is subject to discipline, which may include a failing grade in the course, and may also be subject to more severe discipline by the University. Students are encouraged to visit the link below and become familiar with the Standards for Student Conduct.

<http://www.csun.edu/a&r/soc/studentconduct.html>

### About Plagiarism

Plagiarism means using words, ideas, or arguments from another person or source without citation[^4]. Cite all sources consulted to any extent (including material from the internet), whether or not assigned and whether or not quoted directly. For quotations, four or more words used in sequence must be set off in quotation marks, with the source identified.

[^4]: Except for Homeworks. your hand-in assignments must represent your own thoughts (refer to [Academic Dishonesty Policy](#dishonesty) for more information); especially, the information about PLAGIARISM.

Plagiarism is a serious violation of the CSUN Student Conduct Code. Please read my comment about plagiarism under [Homeworks](#homeworks). Any form of cheating will immediately earn you a failing grade for the entire course. **By remaining enrolled, you consent to this policy**.

> Turnitin (see below) will detect such misconducts as it checks every submission against a database of papers, as well as against the Internet.

What is Turnitin?

[Turnitin](https://www.turnitin.com/) is an automated system that instructors can use to quickly and easily compare each student's assignment with billions of websites, as well as an enormous database of student papers that grows with each submission. Accordingly, you will be expected to submit assignments through the Canvas Assignment Tool in electronic format. After the assignment is processed, as an instructor, I receive a report from *Turnitin* that states if and how another author's work was used in the assignment.

------------------------------------------------------------------------

# Final (yet important) Notes

## How to Access our Course and Get Started

-   Log into Canvas: <https://canvas.csun.edu>
-   Under "My Courses," locate our course and click on it.
-   This will take you to the course home page.

## Technology Requirements and Support:

-   A computer and access to the internet (reliable connection)
-   Google Chrome (web browser)

## What I Expect of You:

1.  Plan your schedule to ensure you several hours per week to spend on this class and take time to identify where and when you'll do your learning.
2.  Review the due dates for the assignments (refer to our Course Schedule in Canvas) to orient yourself to the flow of the learning.
3.  This course requires regular engagement and practice using [jamovi](#supplies) (Statistical Package).

------------------------------------------------------------------------

# How to be Success in this Course

Consider the goals you have for engaging in this course as you determine how to allocate time to complete course requirements.

Each student has a different pace when comes to studying for a course. Thus, I will let you figure out how many hours you need to reserve each week for this course. Regardless of the number of hours chosen, try to divide your time so that you devote more time to `assignments` and `assigned readings`.

The Module Time chart below provides a visual representation of the typical time spent completing a module, followed by an example weekly schedule.

## Module time

A typical module in this course is comprised of the following categories:

1.  Readings + eFlashcards
2.  Mini-lecture
3.  Practice `jamovi`
4.  Assignments (major takeaways, quizzes)

```{r echo=FALSE}
# Pie Chart with Percentages
slices <- c(30, 15, 15, 40)
lbls <- c("Assignments", "Mini-lectures", "Practice jamovi", "Readings+eFlashcards")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels
lbls <- paste(lbls,"%",sep="") # ad % to labels
pie(slices,labels = lbls, main="Module Time") 

```
## Example Weekly Schedule

-  Monday-Tuesday (or get a jump-start on the weekend) 
   -  Read the chapter(s) + Study the eFlashcards
-  Wednesday-Thursday
   -  Watch the mini-lectures + Practice jamovi
-  Friday-Sunday
   - Complete the assignments

# Student Support Services

CSUN aims to make all learning experiences as accessible as possible, and has a variety of resources available to help support students.  If you believe the design of this course poses barriers to effectively participate or demonstrate your learning, please contact me to discuss possible options and adjustments. 

- The IT Help Center (818)677-1400, helpcenter@csun.edu is available to help with Canvas, CSUN e-mail, SOLAR/Portal, and other technical issues.   
- CSUN Device Loaner Program (https://bit.ly/3t1G0An) provides devices that can be checked out that includes laptops, webcams, hotspots and headsets 
- The Learning Resource Center (818) 677-2033  The mission of the LRC is to enable students to improve their academic performance through a variety of learning programs, including workshops, one-on-one and group tutoring, supplemental instruction classes and interactive subject area computer programs and videos.  Student who use the LRC learning programs will develop and strengthen their critical thinking skills, study strategies, writing skills and performance in subject matter courses. 
- University Counseling Services (818) 677-2366, Bayramian Hall 520.  UCS provides resources and information to assist students in dealing with a variety of large and small psychological obstacles that may interfere with academic progress and/or relationship satisfaction.  Services include individual, group, and crisis counseling. 
- In accordance with the CSUN Accessibility Policy (https://bit.ly/3yqGHE9), CSUN is working to ensure that campus communication and course materials are accessible to everyone.  Please reach out to me if you have difficulty with any of the materials for this course. 
- If you have a disability and need accommodations, please register with the Disability Resources and Educational Services (DRES) office or the National Center on Deafness (NCOD). 
  - The DRES office can be reached at (818) 677-2684. 
  - NCOD can be reached at (818) 677-2611. 
  - Reasonable accommodations and services will be provided to students if requests are made in a timely manner and with appropriate documentation 
  - If you would like to discuss your need for accommodations with me, please drop in office hours or contact me to set up an appointment. 
- Food Pantry (https://bit.ly/38nTsVH) at CSUN: Anybody who faces challenges securing food or housing and believes this impacts course performance, should contact CSUN's Food Pantry website and the corresponding contacts. If you also feel comfortable contacting me, the department chair, or the Dean's Office, we can also facilitate assistance. You don't have to be alone in this moment. 
- Emergency MataCare grants (https://bit.ly/2WAZkIz), one-time grants to prevent evictions, urgent child care issues, etc. - DACA (Deferred Action for Childhood Arrivals) Resources: Check out the Central American Resource Center facebook page (https://bit.ly/2Yg0p9z), legal resources listed on CSUN's Educational Opportunity Program (EOP) Dream Center that was created to support all undocumented students & allies (Dream Center flyer). CSUN President Harrison issued a support statement on the CSUN homepage for DACA and resources. 
- Help lines (https://bit.ly/3sYbMOo)(after hours when the University Counseling is closed) for numerous topics/needs (e.g., suicide, drug, rape, LGBQT, military, or any crisis). You don't have to manage these feelings alone. 
- Pride Center (https://bit.ly/3jqNZUi) offers support and resources to lesbian, gay, bisexual, transgender, queer, & questioning students, faculty, & staff. 
- Klotz Student Health Center (https://bit.ly/3zx1Y0s): Numerous health services including primary care, dental, nutritional counseling, acupuncture, massage and lots more. 
- Career Center (https://bit.ly/3jtTcL2) for resume writing & interviewing and much more; Matty's Closet (https://bit.ly/3jAResx) has free professional clothes for students who need interview or professional attire. 
- USU 9https://bit.ly/38uz59j) for more student services; Clubs & Organizations (https://bit.ly/38tBhOa): Hopefully a dozen people have already advised you to "get involved" (https://bit.ly/3ysqYVb) at CSUN in something that interests you. 
- Associated Students (https://bit.ly/3yuWjGT) offers recycling, and a Children's Center providing child care 
- Financial Aid & Scholarships (https://bit.ly/3sYFzqr) offers aid for applications 
- University Library https://bit.ly/3yuIEQ9) for many additional academic resources 
- Veterans Resource Center (https://bit.ly/38qYtg7) assists CSUN students as they transition from military service to academic success.

Title 5, California Code of Regulations,§ 41301. Standards for Student Conduct – (a) Campus Community Values: The university is committed to maintaining a safe and healthy living and learning environment for students, faculty, and staff. Each member of the campus community should choose behaviors that contribute toward this end. Students are expected to be good citizens and to engage in responsible behaviors that reflect well upon their university, to be civil to one another and to others in the campus community, and contribute positively to student and university life. 

CSUN with A HEART 
If you are facing challenges related to food insecurity, housing precarity/homelessness, mental health, access to technology, eldercare/childcare, or healthcare, you can find guidance, help, and resources from CSUN with A HEART (https://www.csun.edu/heart). 

# Class Schedule

Not included here. Please, refer to our Canvas page.
